name: Build Data Files

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Tesseract OCR
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Collate editions
        run: ./build-data.sh
      
      - name: Create release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # 3.0.1
        if: github.ref_type == 'tag'
        with:
          working_directory: out
          files: |
            cards.yaml
            cards.json
            editions.yaml
            editions.json
            printings.yaml
            printings.json
            meta.yaml
            meta.json
